name: EC2 Security Scans

on:
  workflow_dispatch:

jobs:
  sonarqube_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
      - name: Build and analyze with SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=birdorg -Dsonar.projectKey=birdorg

  snyk_scan:
    name: Snyk Scan
    runs-on: ubuntu-latest
    needs: sonarqube_scan
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: Snyk Maven Scan
        uses: snyk/actions/maven@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  owasp_zap_scan:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: snyk_scan
    if: always()
    steps:
      - uses: actions/checkout@v4
      - name: OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://www.zaproxy.org'